version: '2'

services:
  mongo:
    container_name: mongo
    image: mongo:3.0.7
    networks:
      - back
    volumes:
      - /data/db
    command: --smallfiles
  mariadb:
    image: bitnami/mariadb
    networks:
      - back
    volumes:
      - /data/mariadb/data:/bitnami/mariadb/data
      - /data/mariadb/conf:/bitnami/mariadb/conf
    ports:
      - "{{ DB_PORT }}:3306"
    environment:
      MARIADB_PASSWORD: {{ DB_PASSWORD }}
      MARIADB_DATABASE: {{ DB_NAME }}
    restart: on-failure:3
  todo_api_gateway:
    container_name: todo_api_gateway
    build: ./todo_api_gateway
    networks:
      - back
    dns: 8.8.8.8
    ports:
      - "{{ API_GATEWAY_PORT }}:80"
    links:
      - php_todo_api:php
    restart: on-failure:3
  go_todo_api:
    container_name: go_todo_api
    build: ./go_todo_api
    networks:
      - back
    dns: 8.8.8.8
    ports:
     - "{{ GO_TODO_API_PORT }}:3000"
    environment:
      MONGO_HOST: mongo
      GIN_MODE: release
    restart: on-failure:3
  php_todo_api:
    container_name: php_todo_api
    build: ./php_todo_api
    networks:
      - back
    dns: 8.8.8.8
    ports:
      - "{{ PHP_FPM_PORT }}:9000"
    environment:
      APP_ENV: production
      DB_HOST: mariadb
      DB_USER: {{ DB_USER }}
      DB_PASSWORD: {{ DB_PASSWORD }}
      DB_NAME: {{ DB_NAME }}
      DB_PORT: {{ DB_PORT }}
    restart: on-failure:3
  react_todo_web:
    container_name: react_todo_web
    build: ./react_todo_web
    networks:
      - back
    dns: 8.8.8.8
    ports:
      - "{{ REACT_TODO_WEB_PORT }}:3000"
    environment:
      GIN_MODE: release
      TODO_API_ENDPOINT: "http://{{ HOST }}:{{ GO_TODO_API_PORT }}"
    restart: on-failure:3
networks:
  back:
    driver: bridge
