version: '2'

services:
  go_todo_api:
    volumes:
      - ./go_todo_api:/usr/src/app
    command:
      - dev
    environment:
      GIN_MODE: debug
  php_todo_api:
    volumes:
      - ./php_todo_api:/var/www/php_todo_api
    environment:
      APP_ENV: local
  react_todo_web:
    volumes:
      - ./react_todo_web:/usr/src/app
    command:
      - dev
    environment:
      GIN_MODE: debug
